model_list:
  # Mitral AI provider
  - model_name: codestral-latest
    litellm_params:
      model: codestral/codestral-latest
      api_key: os.environ/CODESTRAL_API_KEY

  - model_name: codestral-2501
    litellm_params:
      model: codestral/codestral-2501
      api_key: os.environ/CODESTRAL_API_KEY

  - model_name: codestral-2405
    litellm_params:
      model: codestral/codestral-2405
      api_key: os.environ/CODESTRAL_API_KEY

  # # Open Router provider
  # - model_name: openrouter/deepseek/deepseek-chat-v3-0324
  #   litellm_params:
  #     model: openrouter/deepseek/deepseek-chat-v3-0324:free
  #     api_key: os.environ/OPEN_ROUTER_API_KEY

  # - model_name: openrouter/deepseek/deepseek-v3-base
  #   litellm_params:
  #     model: openrouter/deepseek/deepseek-v3-base:free
  #     api_key: os.environ/OPEN_ROUTER_API_KEY

  # # Groq
  # - model_name: groq/qwen-qwq-32b
  #   litellm_params:
  #     model: groq/qwen-qwq-32b
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/deepseek-r1-distill-llama-70b
  #   litellm_params:
  #     model: groq/deepseek-r1-distill-llama-70b
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/gemma2-9b-it
  #   litellm_params:
  #     model: groq/gemma2-9b-it
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/compound-beta
  #   litellm_params:
  #     model: groq/compound-beta
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/compound-beta-mini
  #   litellm_params:
  #     model: groq/compound-beta-mini
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/distil-whisper-large-v3-en
  #   litellm_params:
  #     model: groq/distil-whisper-large-v3-en
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/llama-3.1-8b-instant
  #   litellm_params:
  #     model: groq/llama-3.1-8b-instant
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/llama-3.3-70b-versatile
  #   litellm_params:
  #     model: groq/llama-3.3-70b-versatile
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/llama-guard-3-8b
  #   litellm_params:
  #     model: groq/llama-guard-3-8b
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/llama3-70b-8192
  #   litellm_params:
  #     model: groq/llama3-70b-8192
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/llama3-8b-8192
  #   litellm_params:
  #     model: groq/llama3-8b-8192
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/meta-llama/llama-4-maverick-17b-128e-instruct
  #   litellm_params:
  #     model: groq/meta-llama/llama-4-maverick-17b-128e-instruct
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/meta-llama/llama-4-scout-17b-16e-instruct
  #   litellm_params:
  #     model: groq/meta-llama/llama-4-scout-17b-16e-instruct
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/mistral-saba-24b
  #   litellm_params:
  #     model: groq/mistral-saba-24b
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/whisper-large-v3
  #   litellm_params:
  #     model: groq/whisper-large-v3
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/whisper-large-v3-turbo
  #   litellm_params:
  #     model: groq/whisper-large-v3-turbo
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/playai-tts
  #   litellm_params:
  #     model: groq/playai-tts
  #     api_key: os.environ/GROQ_API_KEY

  # - model_name: groq/playai-tts-arabic
  #   litellm_params:
  #     model: groq/playai-tts-arabic
  #     api_key: os.environ/GROQ_API_KEY

  # Hugging Face
  - model_name: huggingface/mistralai/Mistral-7B-Instruct-v0.3
    litellm_params:
      model: huggingface/mistralai/Mistral-7B-Instruct-v0.3
      api_key: os.environ/HUGGINGFACE_API_KEY

  - model_name: huggingface/mistralai/Mixtral-8x7B-Instruct-v0.1
    litellm_params:
      model: huggingface/mistralai/Mixtral-8x7B-Instruct-v0.1
      api_key: os.environ/HUGGINGFACE_API_KEY

  - model_name: huggingface/mistralai/Mixtral-8x7B-v0.1
    litellm_params:
      model: huggingface/mistralai/Mixtral-8x7B-v0.1
      api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/microsoft/phi-4
  #   litellm_params:
  #     model: huggingface/microsoft/phi-4
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/meta-llama/Meta-Llama-3-8B-Instruct
  #   litellm_params:
  #     model: huggingface/meta-llama/Meta-Llama-3-8B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-a-03-2025
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-a-03-2025
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-r-08-2024
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-r-08-2024
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-r-plus
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-r-plus
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-r-plus-08-2024
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-r-plus-08-2024
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-r-v01
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-r-v01
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/CohereLabs/c4ai-command-r7b-12-2024
  #   litellm_params:
  #     model: huggingface/CohereLabs/c4ai-command-r7b-12-2024
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/HuggingFaceH4/zephyr-7b-beta
  #   litellm_params:
  #     model: huggingface/HuggingFaceH4/zephyr-7b-beta
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/HuggingFaceTB/SmolLM2-1.7B-Instruct
  #   litellm_params:
  #     model: huggingface/HuggingFaceTB/SmolLM2-1.7B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/NousResearch/Hermes-3-Llama-3.1-405B
  #   litellm_params:
  #     model: huggingface/NousResearch/Hermes-3-Llama-3.1-405B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/NousResearch/Hermes-3-Llama-3.1-8B
  #   litellm_params:
  #     model: huggingface/NousResearch/Hermes-3-Llama-3.1-8B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  #   litellm_params:
  #     model: huggingface/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/QwQ-32B
  #   litellm_params:
  #     model: huggingface/Qwen/QwQ-32B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2-7B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2-7B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-1.5B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-1.5B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-32B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-32B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-72B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-72B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-7B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-7B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-Coder-32B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-Coder-32B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Qwen/Qwen2.5-Coder-7B-Instruct
  #   litellm_params:
  #     model: huggingface/Qwen/Qwen2.5-Coder-7B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/Sao10K/L3-8B-Lunaris-v1
  #   litellm_params:
  #     model: huggingface/Sao10K/L3-8B-Lunaris-v1
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/TinyLlama/TinyLlama-1.1B-Chat-v1.0
  #   litellm_params:
  #     model: huggingface/TinyLlama/TinyLlama-1.1B-Chat-v1.0
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/aaditya/Llama3-OpenBioLLM-70B
  #   litellm_params:
  #     model: huggingface/aaditya/Llama3-OpenBioLLM-70B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/aaditya/Llama3-OpenBioLLM-8B
  #   litellm_params:
  #     model: huggingface/aaditya/Llama3-OpenBioLLM-8B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-R1
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-R1
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-R1-Distill-Llama-8B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-V3
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-V3
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/deepseek-ai/DeepSeek-V3-0324
  #   litellm_params:
  #     model: huggingface/deepseek-ai/DeepSeek-V3-0324
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/google/gemma-2-27b-it
  #   litellm_params:
  #     model: huggingface/google/gemma-2-27b-it
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/google/gemma-2-2b-it
  #   litellm_params:
  #     model: huggingface/google/gemma-2-2b-it
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/google/gemma-2-9b-it
  #   litellm_params:
  #     model: huggingface/google/gemma-2-9b-it
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/google/gemma-2b-it
  #   litellm_params:
  #     model: huggingface/google/gemma-2b-it
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/meta-llama/Llama-2-13b-chat-hf
  #   litellm_params:
  #     model: huggingface/meta-llama/Llama-2-13b-chat-hf
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/meta-llama/Llama-3.1-8B-Instruct
  #   litellm_params:
  #     model: huggingface/meta-llama/Llama-3.1-8B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/meta-llama/Llama-3.2-1B-Instruct
  #   litellm_params:
  #     model: huggingface/meta-llama/Llama-3.2-1B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: huggingface/meta-llama/Llama-3.2-3B
  #   litellm_params:
  #     model: huggingface/meta-llama/Llama-3.2-3B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: meta-llama/Llama-3.2-3B-Instruct
  #   litellm_params:
  #     model: meta-llama/Llama-3.2-3B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: meta-llama/Llama-3.3-70B-Instruct
  #   litellm_params:
  #     model: meta-llama/Llama-3.3-70B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: meta-llama/Llama-Guard-3-8B
  #   litellm_params:
  #     model: meta-llama/Llama-Guard-3-8B
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: meta-llama/Meta-Llama-3-8B-Instruct
  #   litellm_params:
  #     model: meta-llama/Meta-Llama-3-8B-Instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: microsoft/Phi-3-mini-4k-instruct
  #   litellm_params:
  #     model: microsoft/Phi-3-mini-4k-instruct
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: mistralai/Mistral-Small-24B-Instruct-2501
  #   litellm_params:
  #     model: mistralai/Mistral-Small-24B-Instruct-2501
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
  #   litellm_params:
  #     model: nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: nvidia/Llama-3_1-Nemotron-Ultra-253B-v1
  #   litellm_params:
  #     model: nvidia/Llama-3_1-Nemotron-Ultra-253B-v1
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: nvidia/Llama-3_3-Nemotron-Super-49B-v1
  #   litellm_params:
  #     model: nvidia/Llama-3_3-Nemotron-Super-49B-v1
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: openai-community/gpt2
  #   litellm_params:
  #     model: openai-community/gpt2
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: perplexity-ai/r1-1776
  #   litellm_params:
  #     model: perplexity-ai/r1-1776
  #     api_key: os.environ/HUGGINGFACE_API_KEY

  # - model_name: teknium/OpenHermes-2.5-Mistral-7B
  #   litellm_params:
  #     model: teknium/OpenHermes-2.5-Mistral-7B
  #     api_key: os.environ/HUGGINGFACE_API_KEY
